# 导入所有节点确保注册
import core.nodes.base
import core.nodes.input_image
import core.nodes.ocr_node
import core.nodes.stt_listen_node
import core.nodes.stt_history_node
import core.nodes.context_build_node
import core.nodes.llm_node
import core.nodes.tts_node
import core.nodes.ts_output_node
import core.nodes.ts_input_node
